permalink: /post/:title
markdown: kramdown
  
gems: [jekyll-paginate]
encoding: UTF-8
feed: /atom.xml
title: "Victor's Blog"

name: ¸µÎ¬Ïè
url: https://victorfureal.github.io/
description: Victor Fu's Blog.